apiVersion: v1
kind: Secret
metadata:
  name: secrets
data:
  POSTGRES_USER: POSTGRES_USER_VALUE
  POSTGRES_PASSWORD: POSTGRES_PASSWORD_VALUE
  AI21_TOKEN: AI21_TOKEN_VALUE
  REACT_APP_GOOGLE_KEY: REACT_APP_GOOGLE_KEY_VALUE
  