apiVersion: v1
kind: Secret
metadata:
  name: secrets
data:
  POSTGRES_USER: cG9zdGdyZXMK  
  POSTGRES_PASSWORD: MTIzMQo=   
  AI21_TOKEN: bUo0U2ZaVkd1M1luMU10UXFwYk50MU5wemh2YmJFNmkK 
  REACT_APP_GOOGLE_KEY: QUl6YVN5QUFMMUd0R1hwTjNORWdjYlJVcVF2RXpOYVJNazc0MHVNCg== 