apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: jubuitrago/tunefy:prod-backend-0.0.5
        ports:
        - containerPort: 3001
        env:
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_USER
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_PASSWORD
        - name: PGHOST
          valueFrom:
            configMapKeyRef:
              name: configs
              key: POSTGRES_HOST
        - name: PGDATABASE
          valueFrom:
            configMapKeyRef:
              name: configs
              key: POSTGRES_DB
        - name: PGPORT
          valueFrom:
            configMapKeyRef:
              name: configs
              key: PGPORT
        - name: REACT_SERVER_FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: configs
              key: PUBLIC_ALB_URL
        - name: AI21_TOKEN
          valueFrom:
            secretKeyRef:
              name: secrets
              key: AI21_TOKEN
      imagePullSecrets:
      - name: myregistrykey

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001