apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend-deployment
spec:
  replicas: 2  # Cambia el número de réplicas según tu necesidad
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - frontend1
                - frontend2
      containers:
      - name: frontend
        image: jubuitrago/tunefy:prod-frontend-0.0.5
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_GOOGLE_KEY
          valueFrom:
            secretKeyRef:
              name: secrets
              key: REACT_APP_GOOGLE_KEY
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: configs
              key: PUBLIC_ALB_URL
      imagePullSecrets:
      - name: myregistrykey

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
